theme: jekyll-theme-midnight
title: Mengsen's research spot 
description: Oh hey! This is Mengsen Zhang, a current Ph.D. student in Complex Systems and Brain Sciences. This is the spot where I curate stuffs related to my research interests. 
